import type { RepositoryFacts } from "../types.ts";

export function draftAgentsMd(facts: RepositoryFacts): string {
  const lines = [
    "# AGENTS.md",
    "",
    "Generated by Agent-Primer. Review commands before use; this file intentionally lists only detected project behavior.",
    "",
    "## Setup",
    ...commands(facts.setupCommands, "No setup command was detected."),
    environmentSection(facts),
    "",
    "## Build",
    ...commands(facts.buildCommands, "No build command was detected."),
    "",
    "## Test",
    ...commands(facts.testCommands, "No test command was detected; do not claim tests ran without confirming the project documentation."),
    "",
    "## Run",
    ...commands(facts.runCommands, "No development run command was detected."),
    "",
    "## Code style and conventions",
    ...bullets(facts.conventions, "Follow existing patterns in the surrounding code and keep changes scoped."),
    "",
    "## Project structure",
    `- Primary languages: ${facts.languages.join(", ")}.`,
    facts.packageManager !== "unknown" ? `- Detected package manager: ${facts.packageManager}. Do not switch package managers or regenerate a different lockfile.` : "- No package manager was detected.",
    ...bullets(facts.topLevelDirectories.map((directory) => `Top-level directory: \`${directory}/\`.`), "The repository has no notable top-level source directories."),
    ...bullets(facts.entryPoints.map((entry) => `Likely entry point: \`${entry}\`.`), "No conventional entry point was detected."),
    "",
    "## Common gotchas",
    ...bullets(facts.gotchas, "Run commands from the repository root and read command failures carefully before changing configuration."),
    "",
  ];
  return lines.filter((line) => line !== undefined).join("\n");
}

function commands(values: string[], fallback: string): string[] { return values.length ? values.map((value) => `\`\`\`sh\n${value}\n\`\`\``) : [fallback]; }
function bullets(values: string[], fallback: string): string[] { return values.length ? values.map((value) => `- ${value}`) : [`- ${fallback}`]; }
function environmentSection(facts: RepositoryFacts): string {
  if (facts.environmentFiles.length === 0) return "";
  const variables = facts.environmentVariables.length ? ` Expected keys: ${facts.environmentVariables.map((name) => `\`${name}\``).join(", ")}.` : "";
  return `Copy/configure a local environment file as required (${facts.environmentFiles.map((file) => `\`${file}\``).join(", ")}). Never commit secrets.${variables}`;
}
